(import (scheme base) (scheme write))
(display (car (cons 1 2))) (newline)
(display (cdr (cons 1 2))) (newline)
(display (cons 1 2)) (newline)
(display (pair? (cons 1 2))) (newline)
(display (pair? 5)) (newline)
(display (null? '())) (newline)
(display (null? (cons 1 '()))) (newline)
(display '(1 2 3)) (newline)
(display '(1 (2 3) 4)) (newline)
(display '()) (newline)
