(import (scheme base) (scheme write))
(define v (vector (make-parameter 1)))
(let ((p (vector-ref v 0)))
  (parameterize ((p 5))
    (let ((p2 (vector-ref v 0)))
      (display (p2)))))
(newline)
(let ((p3 (vector-ref v 0))) (display (p3)))
(newline)
