(import (scheme base) (scheme write))
(define p (make-parameter 100))
(define (reader) (p))
(define (adder n) (+ (p) n))
(display (reader)) (newline)
(parameterize ((p 7))
  (display (reader)) (newline)
  (display (adder 1)) (newline))
(display (adder 1)) (newline)
