(import (scheme base) (scheme write))
(define p (make-parameter 1))
(display (p)) (newline)
(parameterize ((p 2))
  (display (p)) (newline)
  (parameterize ((p 3))
    (display (p)) (newline))
  (display (p)) (newline))
(display (p)) (newline)
