(import (scheme base) (scheme write))
(define (run limit)
  (call/cc (lambda (return)
    (letrec ((loop (lambda (i sum)
      (if (> sum limit) (return i)
        (loop (+ i 1) (+ sum i))))))
      (loop 0 0)))))
(display (run 20)) (newline)
(display (run 100)) (newline)
