(import (scheme base) (scheme write))
(define (len l) (if (null? l) 0 (+ 1 (len (cdr l)))))
(define (sum l) (if (null? l) 0 (+ (car l) (sum (cdr l)))))
(define (rev l acc) (if (null? l) acc (rev (cdr l) (cons (car l) acc))))
(let ((xs (list 1 2 3 4 5)))
  (display (len xs)) (newline)
  (display (sum xs)) (newline)
  (display (rev xs '())) (newline)
  (display (len '())) (newline))
