(import (scheme base) (scheme write))
(display (guard (e ((eq? e 'a) (list 'A e)) (else (list 'other e)))
  (raise 'a)))
(newline)
(display (guard (e ((eq? e 'a) 'A) (else (list 'else-got e)))
  (raise 'z)))
(newline)
(display (guard (e (else 'unused)) 'normal))
(newline)
(display (guard (e (else 'unused)) #f))
(newline)
